// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xllyuaweghidcdpptbgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbHl1YXdlZ2hpZGNkcHB0Ymd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTI1OTcsImV4cCI6MjA3MTI4ODU5N30.1blA3hP1L2C79yETz_Zgh2X-S272qMtU7XzifWxzaA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});